pipeline {
  agent any
  stages {
    stage("verify tooling") {
      steps {
        bat '''
          docker version
          docker info
          docker compose version 
          curl --version
          '''
      }
    }
    stage('Prune Docker data') {
      steps {
        bat 'docker system prune -a --volumes -f'
      }
    }
    stage('Start container') {
    steps {
        dir('plataformaDeCursosOnline') {
            bat 'docker-compose up -d --no-color --wait'
            bat 'docker-compose ps'
        }
    }
    
    stage('Wait for container to start') {
    steps {
        script {
          sleep 5
        }
      }
    }
}

    stage('Run tests against the container') {
      steps {
        bat 'curl http://localhost:9090'
      }
    }
  }
}